=== Anzhelika-Trockaya/epam-jwd-task2/task2/src/main/resources/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="candy-type">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="25"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element ref="production"/>
            <xs:element ref="expiration-date"/>
            <xs:element name="ingredients">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="ingredient" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="energy" type="xs:positiveInteger"/>
            <xs:element ref="value"/>
        </xs:sequence>
        <xs:attribute name="vendor-code" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="caramel-candy-type">
        <xs:complexContent>
            <xs:extension base="candy-type">
                <xs:sequence>
                    <xs:element name="flavor" type="xs:string"/>
                    <xs:element name="lollipop" type="xs:boolean"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="chocolate-candy-type">
        <xs:complexContent>
            <xs:extension base="candy-type">
                <xs:sequence>
                    <xs:element ref="chocolate-type"/>
                </xs:sequence>
                <xs:attribute name="filling" type="xs:string" use="optional" default="without"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="candy" type="candy-type" abstract="true"/>

    <xs:element name="caramel-candy" type="caramel-candy-type" substitutionGroup="candy"/>

    <xs:element name="chocolate-candy" type="chocolate-candy-type" substitutionGroup="candy"/>

    <xs:element name="ingredient">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ingredient-name" type="xs:string"/>
                <xs:element name="weight" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="value">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="carbohydrates" type="xs:int"/>
                <xs:element name="fats" type="xs:int"/>
                <xs:element name="proteins" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="production">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Kommunarka"/>
                <xs:enumeration value="Spartak"/>
                <xs:enumeration value="Roshen"/>
                <xs:enumeration value="Peter Ronnen"/>
                <xs:enumeration value="Konti"/>
                <xs:enumeration value="Rikki"/>
                <xs:enumeration value="Solyariki"/>
                <xs:enumeration value="Chupa Chups"/>
                <xs:enumeration value="Snickers"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="chocolate-type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Milk"/>
                <xs:enumeration value="Dark"/>
                <xs:enumeration value="White"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="expiration-date">
        <xs:simpleType>
            <xs:restriction base="xs:gYearMonth">
                <xs:pattern value="2[0-9][0-9][0-9]-((0[1-9])|(1[0-2]))"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="candies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="candy" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Anzhelika-Trockaya/epam-jwd-task2/task2/src/main/resources/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="candies.xsd">
    <chocolate-candy vendor-code="1111111">
        <name>Berezka</name>
        <production>Spartak</production>
        <expiration-date>2023-03</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Cacao</ingredient-name>
                <weight>17</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>5</weight>
            </ingredient>
        </ingredients>
        <energy>1300</energy>
        <value>
            <carbohydrates>87</carbohydrates>
            <fats>12</fats>
            <proteins>41</proteins>
        </value>
        <chocolate-type>Dark</chocolate-type>
    </chocolate-candy>
    <chocolate-candy filling="Milk chocolate mass" vendor-code="589614">
        <name>Alenka</name>
        <production>Roshen</production>
        <expiration-date>2023-02</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Cacao</ingredient-name>
                <weight>17</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>5</weight>
            </ingredient>
        </ingredients>
        <energy>2300</energy>
        <value>
            <carbohydrates>110</carbohydrates>
            <fats>46</fats>
            <proteins>25</proteins>
        </value>
        <chocolate-type>Milk</chocolate-type>
    </chocolate-candy>
    <caramel-candy vendor-code="123456">
        <name>Duchesse</name>
        <production>Kommunarka</production>
        <expiration-date>2022-09</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Sugar</ingredient-name>
                <weight>14</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>25</weight>
            </ingredient>
        </ingredients>
        <energy>1452</energy>
        <value>
            <carbohydrates>147</carbohydrates>
            <fats>52</fats>
            <proteins>14</proteins>
        </value>
        <flavor>Duchesse</flavor>
        <lollipop>false</lollipop>
    </caramel-candy>
    <caramel-candy vendor-code="4521365">
        <name>Chupa Chups</name>
        <production>Chupa Chups</production>
        <expiration-date>2023-10</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Sugar</ingredient-name>
                <weight>24</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>10</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Fructose</ingredient-name>
                <weight>5</weight>
            </ingredient>
        </ingredients>
        <energy>380</energy>
        <value>
            <carbohydrates>95</carbohydrates>
            <fats>20</fats>
            <proteins>4</proteins>
        </value>
        <flavor>Strawberry</flavor>
        <lollipop>true</lollipop>
    </caramel-candy>
    <caramel-candy vendor-code="1145214">
        <name>Chupa Chups XXL</name>
        <production>Chupa Chups</production>
        <expiration-date>2022-12</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Sugar</ingredient-name>
                <weight>32</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>20</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Fructose</ingredient-name>
                <weight>14</weight>
            </ingredient>
        </ingredients>
        <energy>560</energy>
        <value>
            <carbohydrates>145</carbohydrates>
            <fats>41</fats>
            <proteins>8</proteins>
        </value>
        <flavor>Apple</flavor>
        <lollipop>true</lollipop>
    </caramel-candy>
    <caramel-candy vendor-code="2245">
        <name>Solyariki</name>
        <production>Solyariki</production>
        <expiration-date>2023-02</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>10</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Fructose</ingredient-name>
                <weight>24</weight>
            </ingredient>
        </ingredients>
        <energy>390</energy>
        <value>
            <carbohydrates>97</carbohydrates>
            <fats>0</fats>
            <proteins>0</proteins>
        </value>
        <flavor>Orange</flavor>
        <lollipop>true</lollipop>
    </caramel-candy>
    <caramel-candy vendor-code="2222222">
        <name>Rikki</name>
        <production>Rikki</production>
        <expiration-date>2022-10</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>14</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Fructose</ingredient-name>
                <weight>35</weight>
            </ingredient>
        </ingredients>
        <energy>256</energy>
        <value>
            <carbohydrates>47</carbohydrates>
            <fats>0</fats>
            <proteins>0</proteins>
        </value>
        <flavor>Mint</flavor>
        <lollipop>false</lollipop>
    </caramel-candy>
    <caramel-candy vendor-code="353535">
        <name>Konti</name>
        <production>Konti</production>
        <expiration-date>2023-10</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>14</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Sugar</ingredient-name>
                <weight>47</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Starch molasses</ingredient-name>
                <weight>75</weight>
            </ingredient>
        </ingredients>
        <energy>380</energy>
        <value>
            <carbohydrates>36</carbohydrates>
            <fats>14</fats>
            <proteins>0</proteins>
        </value>
        <flavor>Caramel</flavor>
        <lollipop>false</lollipop>
    </caramel-candy>
    <chocolate-candy filling="Hazelnut" vendor-code="848586">
        <name>Teddy bear in the meadow</name>
        <production>Kommunarka</production>
        <expiration-date>2023-05</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Cacao</ingredient-name>
                <weight>25</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>10</weight>
            </ingredient>
        </ingredients>
        <energy>760</energy>
        <value>
            <carbohydrates>550</carbohydrates>
            <fats>24</fats>
            <proteins>325</proteins>
        </value>
        <chocolate-type>Milk</chocolate-type>
    </chocolate-candy>
    <chocolate-candy filling="Peanut" vendor-code="777814">
        <name>Choconut</name>
        <production>Peter Ronnen</production>
        <expiration-date>2023-02</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Cacao</ingredient-name>
                <weight>23</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>5</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Peanut</ingredient-name>
                <weight>45</weight>
            </ingredient>
        </ingredients>
        <energy>754</energy>
        <value>
            <carbohydrates>642</carbohydrates>
            <fats>65</fats>
            <proteins>12</proteins>
        </value>
        <chocolate-type>Dark</chocolate-type>
    </chocolate-candy>
    <chocolate-candy filling="Marmalade" vendor-code="66547">
        <name>Sladunitsa</name>
        <production>Kommunarka</production>
        <expiration-date>2023-04</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Cacao</ingredient-name>
                <weight>17</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>5</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Sugar</ingredient-name>
                <weight>78</weight>
            </ingredient>
        </ingredients>
        <energy>456</energy>
        <value>
            <carbohydrates>410</carbohydrates>
            <fats>0</fats>
            <proteins>15</proteins>
        </value>
        <chocolate-type>Milk</chocolate-type>
    </chocolate-candy>
    <chocolate-candy filling="Peanut, Caramel" vendor-code="555614">
        <name>Peanuts</name>
        <production>Spartak</production>
        <expiration-date>2022-03</expiration-date>
        <ingredients>
            <ingredient>
                <ingredient-name>Cacao</ingredient-name>
                <weight>45</weight>
            </ingredient>
            <ingredient>
                <ingredient-name>Water</ingredient-name>
                <weight>15</weight>
            </ingredient>
        </ingredients>
        <energy>632</energy>
        <value>
            <carbohydrates>412</carbohydrates>
            <fats>25</fats>
            <proteins>46</proteins>
        </value>
        <chocolate-type>Milk</chocolate-type>
